#' @title Check compatibility
#' @description Function to check whether the data object has been compiled by the traits.build workflow and 
#' therefore has a data structure that is appropriate for use with austraits functions.
#' @param austraits dataframe generated by traits build
#'
#' @return logical (T/F) output
#'
#' @examples
#' \dontrun{
#' check_compatibility(austraits)
#' }
#' @author Elizabeth Wenk - e.wenk@unsw.edu.au

check_compatibility <- function(austraits) {
  
  compiled_by_traits.build <-
    austraits$metadata$related_identifiers %>% 
    util_list_to_df2() %>%
    filter(relation_type == "isCompiledBy", stringr::str_detect(identifier, "github.com/traitecoevo/traits.build"))
  
  if(nrow(compiled_by_traits.build) > 0) {
    TRUE
  } else{
    FALSE
  }
  
}
