#' @title Check compatibility
#' @description Function to check whether the data object has been compiled by the traits.build workflow and 
#' therefore has a data structure that is appropriate for use with austraits functions.
#' @param austraits dataframe generated by traits build
#'
#' @return logical (T/F) output and messaging for uncompatible versions
#'
#' @examples
#' \dontrun{
#' check_compatibility(austraits)
#' }
#' @author Elizabeth Wenk - e.wenk@unsw.edu.au

check_compatibility <- function(austraits) {
  
  if (is.null(austraits$metadata)) {
    
    compatible <- FALSE
    
    # message("You are working with AusTraits version 3.0 or earlier. \nThis database structure is unsupported by the current version of this package. \nPlease see https://github.com/traitecoevo/austraits for details on installing old versions of the package.")
    
  } else {
    
    compiled_by_traits.build <-
      austraits$metadata$related_identifiers %>% 
      util_list_to_df2() %>%
      filter(relation_type == "isCompiledBy", stringr::str_detect(identifier, "github.com/traitecoevo/traits.build"))
    
    if(is.null(compiled_by_traits.build) | nrow(compiled_by_traits.build) > 0) {
      compatible <- TRUE
    } else{
      compatible <- FALSE
      
      # message("You are working with AusTraits version 4, which is unsupported by the current version of this package. \nPlease see https://github.com/traitecoevo/austraits for details on installing old versions of the package.")
    }
    
  }
  
  invisible(compatible)
  
}
