#' @title Join study details into main `traits` dataset
#' @description Function to append all study information (method, location, taxonomic, context) variables into trait database
#' @param austraits dataframe generated by austraits build
#' @param ... arguments passed to vars to select relevant column names from their respective tables
#' @return austraits list object, but with additional variables appended to `traits` dataframe
#' @rdname join_all
#' @importFrom rlang .data
#' @examples
#' \dontrun{
#' austraits$traits
#' 
#' #Append sites data
#' (austraits %>% join_sites)$traits
#'
#' #Append contexts
#' (austraits %>% join_contexts)$traits
#' 
#' # Append methods
#' (austraits %>% join_methods)$traits
#' 
#' #Append taxonomic details
#' (austraits %>% join_taxonomy)$traits
#' 
#' #Append all information
#' (austraits %>% join_all)$traits
#' }
#' @author Daniel Falster - daniel.falster@unsw.edu.au
#' @export


join_all <- function(austraits) {
  austraits %>% 
    join_locations() %>% 
    join_taxonomy() %>% 
    join_methods()
}

#' @title Joining taxonomic information to traits table
#' @export
#' @importFrom rlang .data
#' @rdname join_all

join_taxonomy <- function(austraits, ...) {
  # Switch for different versions
  version <- austraits$build_info$version %>% as.character()
  
  switch (version,
          '3.0.2.9000' = join_taxonomy2(austraits, ...),
          '3.0.2' = join_taxonomy1(austraits, ...),
          '3.0.1' = join_taxonomy1(austraits, ...),
          '3.0.0' = join_taxonomy1(austraits, ...),
          '2.1.0' = join_taxonomy1(austraits, ...),
          '2.0.0' = join_taxonomy1(austraits, ...),

  )
  
}

#' @title  Joining taxonomic info for AusTraits versions <= 3.0.2

join_taxonomy1 <- function(austraits, vars =  c("family", "genus", "taxonRank", "acceptedNameUsageID")) {
  austraits$traits <- austraits$traits %>%
    dplyr::left_join(by="taxon_name", austraits$taxa %>% dplyr::select("taxon_name", tidyselect::any_of(vars)))
  
  austraits
}

#' @title Joining taxonomic info for AusTraits versions > 3.0.2

join_taxonomy2 <- function(austraits, vars =  c("family", "genus", "taxon_rank", "accepted_name_usage_id")) {
  austraits$traits <- austraits$traits %>%
    dplyr::left_join(by="taxon_name", austraits$taxa %>% dplyr::select("taxon_name", tidyselect::any_of(vars)))
  
  austraits
}

#' @title Joining methodological information to traits table
#' @importFrom rlang .data
#' @export
#' @rdname join_all

join_methods <- function(austraits, vars =  c("methods", "year_collected_start", "year_collected_end", "collection_type")) {
  austraits$methods %>% 
    dplyr::select(c("dataset_id", "trait_name"), tidyselect::any_of(vars)) -> methods
  
  austraits$traits <- austraits$traits %>%
      dplyr::left_join(by=c("dataset_id", "trait_name"),
                       methods)
    
    austraits
}

join_methods2 <- function(austraits, vars =  c("methods", "year_collected_start", "year_collected_end", "collection_type")) {
  austraits$methods %>% 
    dplyr::select(c("dataset_id", "trait_name"), tidyselect::any_of(vars)) %>% 
    distinct() -> methods
  
  austraits$traits <- austraits$traits %>%
    dplyr::left_join(by=c("dataset_id", "trait_name"),
                     methods)
  
  austraits
}

#' @title Joining location information to traits table
#' @export
#' @importFrom rlang .data
#' @rdname join_all

join_locations <- function(austraits, ...) {
  # Switch for different versions
  version <- austraits$build_info$version %>% as.character()
  
  switch (version,
          '3.0.2.9000' = join_locations2(austraits, ...),
          '3.0.2' = join_sites(austraits, ...),
          '3.0.1' = join_sites(austraits, ...),
          '3.0.0' = join_sites(austraits, ...),
          '2.1.0' = join_sites(austraits, ...),
          '2.0.0' = join_sites(austraits, ...)
          
  )
}

#' @title  Joining location info for AusTraits versions <= 3.0.2
#' @aliases join_locations
join_sites <- function(austraits, vars =  c("longitude (deg)","latitude (deg)")) {
  sites <- 
    austraits$sites %>% 
    dplyr::filter(.data$site_property %in%  vars) %>% 
    tidyr::pivot_wider(names_from = .data$site_property, values_from = .data$value)
  
  austraits$traits <- austraits$traits %>%
    dplyr::left_join(by=c("dataset_id", "site_name"), sites)
  
  austraits
}

#' @title  Joining location info for AusTraits versions > 3.0.2
join_locations2 <- function(austraits, vars =  c("longitude (deg)","latitude (deg)")) {
  sites <- 
    austraits$locations %>% 
    dplyr::filter(.data$location_property %in%  vars) %>% 
    tidyr::pivot_wider(names_from = .data$location_property)
  
  austraits$traits <- austraits$traits %>%
    dplyr::left_join(by=c("dataset_id", "location_id"), sites)
  
  austraits
}

#' @importFrom rlang .data
#' @export
#' @rdname join_all

join_contexts <- function(austraits, ...){
  # Switch for different versions
  version <- austraits$build_info$version %>% as.character()
  
  switch (version,
          '3.0.2.9000' = join_contexts2(austraits, ...),
          '3.0.2' = join_contexts1(austraits, ...),
          '3.0.1' = join_contexts1(austraits, ...),
          '3.0.0' = join_contexts1(austraits, ...),
          '2.1.0' = join_contexts1(austraits, ...),
          '2.0.0' = join_contexts1(austraits, ...)
          
  )
}

#' @title  Joining location info for AusTraits versions > 3.0.2
join_contexts2 <- function(austraits, ...){
  traits2 <- austraits$traits
  
  for(v in unique(austraits$contexts$link_id)){
    
    context_sub <- 
      austraits$contexts %>%
      dplyr::select(-dplyr::any_of(c("category", "description"))) %>%
      dplyr::filter(link_id == v) %>% 
      tidyr::separate_rows(link_vals) %>% 
      tidyr::pivot_wider(values_from = value, names_from = context_property) %>%
      tidyr::pivot_wider(names_from = link_id, values_from = link_vals)
    
    traits2 <- 
      left_join(by = c("dataset_id", v),
                traits2,
                context_sub
      )
  }
  austraits$traits <- traits2
  austraits
}

#' @title  Joining location info for AusTraits versions <= 3.0.2
join_contexts1 <- function(austraits, vars =  c("dataset_id","context_name","context_property","value")) {
  
  if(nrow(austraits$contexts) == 0)
    return (austraits)
  
  contexts <- 
    austraits$contexts %>% 
    dplyr::filter(.data$context_property %in%  vars) %>% 
    tidyr::pivot_wider(names_from = .data$context_property, values_from = .data$value)
  
  austraits$traits <- austraits$traits %>%
    dplyr::left_join(by=c("dataset_id", "context_name"), contexts)
  
  austraits
}





###