#' @title Join study details into main `traits` dataset
#' @description Function to append all study information (method, site, taxonomic, context) variables into trait database
#' @param austraits dataframe generated by austraits build
#' @param vars variables from other data tables that can be joined
#' @return austraits list object, but with additional variables appended to `traits` dataframe
#' @rdname join_all
#' @importFrom rlang .data
#' @examples
#' \dontrun{
#' austraits$traits
#' 
#' #Append sites data
#' (austraits %>% join_sites)$traits
#'
#' #Append contexts
#' (austraits %>% join_contexts)$traits
#' 
#' # Append methods
#' (austraits %>% join_methods)$traits
#' 
#' #Append taxonomic details
#' (austraits %>% join_taxonomy)$traits
#' 
#' #Append all information
#' (austraits %>% join_all)$traits
#' }
#' @author Daniel Falster - daniel.falster@unsw.edu.au
#' @export

join_all <- function(austraits) {
  austraits %>% 
    join_sites() %>% 
    join_taxonomy() %>% 
    join_methods()
}


#' @importFrom rlang .data
#' @export
#' @rdname join_all
#' 
join_taxonomy <- function(austraits, vars =  c("family", "genus", "taxonRank", "acceptedNameUsageID")) {
  austraits$traits <- austraits$traits %>%
    dplyr::left_join(by="taxon_name", austraits$taxa %>% dplyr::select("taxon_name", tidyselect::any_of(vars)))
  
  austraits
}

#' @importFrom rlang .data
#' @export
#' @rdname join_all
join_methods <- function(austraits, vars =  c("methods", "year_collected_start", "year_collected_end", "collection_type")){
  austraits$traits <- austraits$traits %>%
    dplyr::left_join(by=c("dataset_id", "trait_name"), austraits$methods %>% dplyr::select(c("dataset_id", "trait_name"), tidyselect::any_of(vars)))
  
  austraits
}

#' @export
#' @importFrom rlang .data
#' @rdname join_all
join_sites <- function(austraits, vars =  c("longitude (deg)","latitude (deg)")) {
  sites <- 
    austraits$sites %>% 
    dplyr::filter(.data$site_property %in%  vars) %>% 
    tidyr::pivot_wider(names_from = .data$site_property, values_from = .data$value)
  
  austraits$traits <- austraits$traits %>%
    dplyr::left_join(by=c("dataset_id", "site_name"), sites)
  
  austraits
}

#' @importFrom rlang .data
#' @export
#' @rdname join_all
join_contexts <- function(austraits, vars =  c("dataset_id","context_name","context_property","value")) {
  
  if(nrow(austraits$contexts) == 0)
    return (austraits)
  
  contexts <- 
    austraits$contexts %>% 
    dplyr::filter(.data$context_property %in%  vars) %>% 
    tidyr::pivot_wider(names_from = .data$context_property, values_from = .data$value)
  
  austraits$traits <- austraits$traits %>%
    dplyr::left_join(by=c("dataset_id", "context_name"), contexts)
  
  austraits
}
